### ISSUE TITLE
Add a way to spec images for landing page carousel 

### ISSUE THREAD

**Issue by toto** [nandorocker/evenly-web#18]

**Comment by toto** [comment]
We can hard code this for launch

**Comment by toto** [comment]
![screen shot 2015-12-01 at 17 51 18](https://cloud.githubusercontent.com/assets/15453/11507423/3c12790a-9854-11e5-9d9b-cc1f7c422acb.png)

**Comment by nandorocker** [comment]
Documented on the README. Creating an issue for implementing this in CSS later.
