### ISSUE TITLE
Wrong font in animation

### ISSUE THREAD

**Issue by nandorocker** [nandorocker/evenly-web#6]
The font should be Avenir as the rest of the site
![1aeab126-9371-11e5-91f4-bcfd3828d71a](https://cloud.githubusercontent.com/assets/1476836/11400965/9506ee92-9390-11e5-9879-5fb080e8694c.png)

**Comment by nandorocker** [comment]
Fixed!

**Comment by toto** [comment]
Still broken for largest window size (font on TV), fixed in smaller ones

**Comment by nandorocker** [comment]
Should be ok now
